name: push-workflow 1
on: push

jobs:
  push-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello seungwan
    - name: step2
      run: |
        echo hello 
        echo github action
