name: environment
on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
    - name: check env & secret  # ORG 또는 Repo에 설정된 값 조회 (Repo가 우선순위가 높음)
      run: |
        echo ${{ vars.level }}
        echo ${{ secrets.key }}

  get-env-dev:
    runs-on: ubuntu-latest
    environment: dev  # environment 설정된 값 조회
    steps:
    - name: check env & secret
      run: |
        echo ${{ vars.level }}
        echo ${{ secrets.key }}