name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 2분후 종료 (job level)
    steps:
    - name: loop
      run: |
        count=0
        while true; do
          echo "seconds: $count"
          count=$((count+1))
          sleep 1
        done
      timeout-minutes: 1  # 1분후 종료 (step level)
    - name: echo # timeout에 의해 종료되면 수행되지 않음
      run: echo hello