name: pull-request-workflow
on: 
  pull_request:
    types: [opened]

jobs:
  push-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello
    - name: step2
      run: |
        echo this is pull request test
